name: Build & Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm

    - name: Build
      run: npm ci && npm run ghbuild

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        cname: android.blueedge.me
        publish_dir: ./build
