name: issue-text

on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
    - uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "Hey, thank you for creating an issue. We will normally respond within 24 hours."
        GITHUB_TOKEN: ${{ secrets.BOT }}
        
    - uses: stefanbuck/github-issue-parser@v2
      id: issue-parser
      with:
        template-path: .github/ISSUE_TEMPLATE/bug_report.yml

    - name: Set labels based on browsers field
      uses: redhat-plumbers-in-action/advanced-issue-labeler@v1
      with:
        issue-form: ${{ steps.issue-parser.outputs.jsonString }}
        section: browsers
        block-list: |
          Other Browser
        token: ${{ secrets.GITHUB_TOKEN }}
